apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.clusterrolebind.name }}
{{- with .Values.clusterrolebind.subjects }}
subjects:
  {{- toYaml . | nindent 4 }}
{{- end }}
{{- with .Values.clusterrolebind.roleRef }}
roleRef:
  {{- toYaml . | nindent 4 }}
{{- end }}
